### ISSUE TITLE
TypeError: weights.every is not a function

### ISSUE THREAD

**Issue by njzjz** [reymond-group/smilesDrawer#161]
After the version was bumped from v2.0.3 to v2.1.2, I got the following error:

```
TypeError: weights.every is not a function
    at module.exports.drawWeights (smiles-drawer.min.js:56:216581)
    at module.exports.draw (smiles-drawer.min.js:56:208856)
    at bundle.js:2:12354
    at SmilesDrawer.parse (smiles-drawer.min.js:1:1751)
    at f (bundle.js:2:12331)
    at HTMLDivElement.<anonymous> (bundle.js:2:9746)
    at Function.each (jquery.min.js:2:3003)
    at S.fn.init.each (jquery.min.js:2:1481)
    at l (bundle.js:2:9664)
    at Object.callback (bundle.js:2:11161)
```

The error disappeared after reverting to the previous version. From the traceback, the error should happen here:

https://github.com/reymond-group/smilesDrawer/blob/667680960074365ae2b93f09a468c75a7872d4c4/src/SvgDrawer.js#L410

**Comment by daenuprobst** [comment]
Did you encounter this error in every browser or was it unique to Internet Explorer 11?

**Comment by njzjz** [comment]
> was it unique to Internet Explorer 11

My browser is Edge 108.0.1462.54.

**Comment by njzjz** [comment]
You can take a look at my application.
[v2.0.8](https://reacnetgenerator.njzjz.win/report?jdata=https%3A%2F%2Fgist.githubusercontent.com%2Fnjzjz%2Fe9a4b42ceb7d2c3c7ada189f38708bf3%2Fraw%2F83d01b9ab1780b0ad2d1e7f934e61fa113cb0f9f%2Fmethane.json)
![image](https://user-images.githubusercontent.com/9496702/210770579-86b010bc-a8b7-481a-90ca-e4bfebb5a213.png)

[v2.1.2](https://ed2a10e6.reacnetgenerator.pages.dev/report?jdata=https%3A%2F%2Fgist.githubusercontent.com%2Fnjzjz%2Fe9a4b42ceb7d2c3c7ada189f38708bf3%2Fraw%2F83d01b9ab1780b0ad2d1e7f934e61fa113cb0f9f%2Fmethane.json)
![image](https://user-images.githubusercontent.com/9496702/210770661-e74e7ea6-b61b-4e26-885f-acada6798a8f.png)

I catch the error and make it fallback to pure texts, but the error message can still be shown in the console.

**Comment by dwrolvink** [comment]
Can confirm. This project's own example file can recreate this:
https://github.com/reymond-group/smilesDrawer/blob/master/example/index_svg.html

Changing the line:
https://github.com/reymond-group/smilesDrawer/blob/67bd1065fef1d7fb6246db7d6ded758c6f43a91a/example/index_svg.html#L11

To:
`<script src="https://unpkg.com/smiles-drawer@2.0.3/dist/smiles-drawer.min.js"></script>`

Works, while setting the version to 2.1.5 gives this error, as well as using the smiles-drawer currently in dist.

**Comment by xavierholt** [comment]
This should be fixed as of v2.1.8 (#191).  It's not yet available on NPM, but you can grab it from the `dist` folder in this repo.

**Comment by njzjz** [comment]
Thanks! Hope the package can be released to npm.
